SETTINGS = [
    {
        "name": "High-contrast colors",
        "attr": "high_contrast_colors",
        "type": "bool",
        "default": False,
        "description": "Make close-to-invisible colors (like dark gray, black or dark blue) visible!",
        "accepted": ['Off', 'On'],
    },
    {
        "name": "Simplify tutorials",
        "attr": "simplify_tutorials",
        "type": "bool",
        "default": False,
        "description": "Use shorter tutorials and simpler wording in menus.",
        "accepted": ['Off', 'On'],
    },
    {
        "name": "Reduce motion",
        "attr": "reduce_motion",
        "type": "bool",
        "default": False,
        "description": "Eviscerate every single animation - all of them at once.",
        "accepted": ['Off', 'On'],
    },
    {
        "name": "Flash effects",
        "attr": "flash_effects",
        "disabled": True,
        "type": "bool",
        "default": True,
        "description": "Enable screen flashes during heavy attacks, transitions or animations.",
        "accepted": ['Off', 'On'],
    },
    {
        "name": "Confirm with double-tapping",
        "attr": "double_tap_confirmation",
        "type": "bool",
        "default": False,
        "description": "Double-tap instead of holding to confirm important stuff.",
        "accepted": ['Off', 'On'],
    },
    {
        "name": "Confirmation hold duration",
        "attr": "confirmation_hold_duration",
        "type": "slider",
        "display": "duration",
        "min": 0.5,
        "max": 3.0,
        "step": 0.1,
        "default": 1.2,
        "description": "How long do you want to hold your keys to confirm important stuff?",
        "suffix": "s",
        "accepted": "0.5-3.0s",
    },
    {
        "name": "Auto-advance dialogue",
        "attr": "auto_advance_dialogue",
        "disabled": True,
        "type": "bool",
        "default": False,
        "description": "Continue dialogue without you having to mash Space.",
        "accepted": ['Off', 'On'],
    },
]
