SETTINGS = [
    {
        "name": "Number format",
        "attr": "number_format",
        "type": "choice",
        "choices": ['Full', 'Compact'],
        "default": "Full",
        "description": "Show full numbers or abbreviations such as 12.5k.",
        "accepted": ['Full', 'Compact'],
    },
    {
        "name": "Display enemy health as...",
        "attr": "battle_health_display",
        "type": "choice",
        "choices": ['Number', 'Bar', 'Both number and bar'],
        "default": "Both number and bar",
        "description": "Choose how enemy health is shown during battles.",
        "accepted": ['Number', 'Bar', 'Both number and bar'],
    },
    {
        "name": "Menu background decoration",
        "attr": "menu_background_decoration",
        "type": "bool",
        "default": True,
        "description": "Show stars on the main menu at night.",
        "accepted": ['Off', 'On'],
    },
    {
        "name": "Rainbow text",
        "attr": "rainbow_text",
        "type": "bool",
        "default": True,
        "description": "Show rainbow colors on decorated text.",
        "accepted": ['Off', 'On'],
    },
    {
        "name": "Text shine",
        "attr": "text_shine",
        "type": "bool",
        "default": True,
        "description": "Play a moving shine across text.",
        "accepted": ['Off', 'On'],
    },
    {
        "name": "Flipboard animations",
        "attr": "flipboard_animations",
        "type": "bool",
        "default": True,
        "description": "Animate letters when text changes.",
        "accepted": ['Off', 'On'],
    },
    {
        "name": "Animation speed",
        "attr": "animation_speed",
        "type": "slider",
        "display": "animation_speed",
        "min": 0.5,
        "max": 2.0,
        "step": 0.1,
        "default": 1.0,
        "description": "Control how fast text animations - like shining, rainbow or flipboard animations - play out!",
        "accepted": "0.5x–2x (1x by default)",
    },
    {
        "name": "Menu transitions",
        "attr": "menu_transitions",
        "type": "bool",
        "default": True,
        "description": "Smooth transitions when moving between menus.",
        "accepted": ['Off', 'On'],
    },
    {
        "name": "Skip startup animation",
        "attr": "disable_startup_animation",
        "type": "bool",
        "default": False,
        "description": "Bypass the startup animation and dive straight into the game.",
        "accepted": ['Off', 'On'],
    },
]
