SETTINGS = [
    {
        "name": "Enemy difficulty",
        "attr": "battle_difficulty",
        "type": "slider",
        "display": "difficulty",
        "min": 0,
        "max": 3,
        "step": 1,
        "default": 1,
        "description": "Choose how hard you want your enemies to be. (Easy - Hard changes stats, Extreme adds new AI.)",
        "accepted": ['Easy', 'Normal', 'Hard', 'Extreme'],
    },
    {
        "name": "New turn starts after...",
        "attr": "battle_turn_delay",
        "type": "slider",
        "display": "duration",
        "min": 0.2,
        "max": 2.0,
        "step": 0.1,
        "default": 1.0,
        "suffix": "s",
        "description": "Set how much to wait after the last action in a turn.",
        "accepted": "0.2-2 sec.",
    },
    {
        "name": "Player health display",
        "attr": "player_health_display",
        "type": "choice",
        "choices": ['Number', 'Bar', 'Both number and bar'],
        "default": "Both number and bar",
        "description": "Choose how your health is shown during battles.",
        "accepted": ['Number', 'Bar', 'Both number and bar'],
    },
    {
        "name": "Battle details",
        "attr": "battle_details",
        "type": "choice",
        "choices": ['Basic', 'Detailed'],
        "default": "Detailed",
        "description": "How much information do you want to see about your enemies during battles?",
        "accepted": ['Basic', 'Detailed'],
    },
    {
        "name": "Shorten action log",
        "attr": "battle_short_action_log",
        "type": "bool",
        "default": False,
        "description": "Display shorter battle messages to reduce read time.",
        "accepted": ['Off', 'On'],
    },
    {
        "name": "Action history length",
        "attr": "battle_action_history_length",
        "type": "choice",
        "choices": [1, 3, 5],
        "default": 1,
        "description": "How many previous battle actions do you want to see?",
        "accepted": ['1', '3', '5'],
    },
    {
        "name": "Victory celebration",
        "attr": "victory_celebration",
        "type": "slider",
        "display": "victory_celebration",
        "min": 0,
        "max": 3,
        "step": 1,
        "default": 2,
        "description": "How big of a party do you want to throw after a victory?",
        "accepted": ['Minimal', 'Small', 'Regular', 'Extreme'],
    },
]
