"""Menu input preferences."""

SETTINGS = [
    {
        "name": "Mouse controls",
        "attr": "mouse_controls",
        "type": "bool",
        "default": True,
        "description": "Enable mouse controls for menus and battles.",
        "accepted": ['Off', 'On'],
    },
    {
        "name": "Move up",
        "attr": "menu_up",
        "type": "keybind",
        "conflict_group": "menu",
        "default": "w",
        "description": "Move up a notch in menus where you're able to move freely. This does not affect arrow key navigation.",
        "accepted": "Any non-reserved key",
        "reserved_keys": ['enter', 'space', 'backspace', 'u', 'l', 'e', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
    },
    {
        "name": "Move down",
        "attr": "menu_down",
        "type": "keybind",
        "conflict_group": "menu",
        "default": "s",
        "description": "Move down a notch in menus where you're able to move freely. This does not affect arrow key navigation.",
        "accepted": "Any non-reserved key",
        "reserved_keys": ['enter', 'space', 'backspace', 'u', 'l', 'e', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
    },
    {
        "name": "Move left",
        "attr": "menu_left",
        "type": "keybind",
        "conflict_group": "menu",
        "default": "a",
        "description": "Move left a notch in menus where you're able to move freely. This does not affect arrow key navigation.",
        "accepted": "Any non-reserved key",
        "reserved_keys": ['enter', 'space', 'backspace', 'u', 'l', 'e', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
    },
    {
        "name": "Move right",
        "attr": "menu_right",
        "type": "keybind",
        "conflict_group": "menu",
        "default": "d",
        "description": "Move right a notch in menus where you're able to move freely. This does not affect arrow key navigation.",
        "accepted": "Any non-reserved key",
        "reserved_keys": ['enter', 'space', 'backspace', 'u', 'l', 'e', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
    },
    {
        "name": "Open inventory",
        "attr": "open_inventory",
        "type": "keybind",
        "conflict_group": "shortcuts",
        "default": "i",
        "description": "Set what key opens the inventory from the house or main menu.",
        "accepted": "Any non-reserved key",
        "reserved_keys": ['b', 'q', '1', 'e', 'r', 'g', 'x', 'o', 't', 'k'],
    },
    {
        "name": "Open character",
        "attr": "open_character",
        "type": "keybind",
        "conflict_group": "shortcuts",
        "default": "c",
        "description": "Set what key opens the character screen from the house or main menu.",
        "accepted": "Any non-reserved key",
        "reserved_keys": ['b', 'q', '1', 'e', 'r', 'g', 'x', 'o', 't', 'k'],
    },
    {
        "name": "Open Settings",
        "attr": "open_settings",
        "type": "keybind",
        "conflict_group": "shortcuts",
        "default": "s",
        "description": "Set what key opens settings from the house or main menu.",
        "accepted": "Any non-reserved key",
        "reserved_keys": ['b', 'q', '1', 'e', 'r', 'g', 'x', 'o', 't', 'k'],
    },
]
