SETTINGS = [
    {
        "name": "Sort items automatically",
        "attr": "sort_items_automatically",
        "type": "bool",
        "default": True,
        "description": "It's in the name. Sorts items automatically!",
        "accepted": ["Off", "On"],
    },
    {
        "name": "Remember last selection",
        "attr": "remember_last_inventory_selection",
        "type": "bool",
        "default": False,
        "description": "Pick up right where you left off when re-opening your bag.",
        "accepted": ["Off", "On"],
    },
    {
        "name": "Item level-up mode",
        "attr": "item_level_up_mode",
        "type": "choice",
        "choices": ["All", "One at a time"],
        "value_labels": {
            "All": "As many levels as possible",
            "One at a time": "One level at a time",
        },
        "default": "All",
        "description": "Choose whether upgrading items happens step-by-step or all at once.",
        "accepted": ["All", "One at a time"],
    },
    {
        "name": "Sort items by...",
        "attr": "inventory_sorting",
        "type": "choice",
        "choices": ["Name", "Level", "Rarity"],
        "default": "Name",
        "description": "Select the primary criteria for sorting items.",
        "accepted": ["Name", "Level", "Rarity"],
    },
    {
        "name": "...and in what order?",
        "attr": "inventory_sort_order",
        "type": "choice",
        "choices": ["Ascending", "Descending"],
        "default": "Ascending",
        "description": "Set the direction of your selected sorting criteria.",
        "accepted": ["Ascending", "Descending"],
    },
]
