SETTINGS = [
    {
        "name": "Sort items automatically",
        "attr": "sort_items_automatically",
        "type": "bool",
        "default": True,
        "description": "It's in the name. Sorts items automatically!",
        "accepted": ['Off', 'On'],
    },
    {
        "name": "Sort items by...",
        "attr": "inventory_sorting",
        "type": "choice",
        "choices": ['Name', 'Level', 'Rarity'],
        "default": "Name",
        "description": "Select the primary criteria for sorting items.",
        "accepted": ['Name', 'Level', 'Rarity'],
    },
    {
        "name": "...and in what order?",
        "attr": "inventory_sort_order",
        "type": "choice",
        "choices": ['Ascending', 'Descending'],
        "default": "Ascending",
        "description": "Set the direction of your selected sorting criteria.",
        "accepted": ['Ascending', 'Descending'],
    },
    {
        "name": "Remember last selection",
        "attr": "remember_last_inventory_selection",
        "type": "bool",
        "default": False,
        "description": "Constantly switching between screens? This will remember the last selected item in your inventory.",
        "accepted": ['Off', 'On'],
    },
    {
        "name": "Compare against equipped item",
        "attr": "compare_equipped_item",
        "type": "bool",
        "default": False,
        "description": "Adds a tiny row into the item information for quick comparison against what you have equipped!",
        "accepted": ['Off', 'On'],
    },
    {
        "name": "Weapon comparison metric",
        "attr": "weapon_comparison_metric",
        "type": "choice",
        "choices": ['Normal damage', 'Critical damage', 'Average damage'],
        "default": "Average damage",
        "description": "What do you want to focus on when you put 2 weapons side by side in the comparison screen?",
        "accepted": ['Normal damage', 'Critical damage', 'Average damage'],
    },
    {
        "name": "Item level-up mode",
        "attr": "item_level_up_mode",
        "type": "choice",
        "choices": ['All', 'One at a time'],
        "value_labels": {'All': 'As many levels as possible', 'One at a time': 'One level at a time'},
        "default": "All",
        "description": "Choose whether upgrading items happens step-by-step or all at once.",
        "accepted": ['All', 'One at a time'],
    },
]
