SETTINGS = [
    {
        "name": "Back",
        "attr": "back",
        "type": "keybind",
        "conflict_group": "menu",
        "allowed_keys": ['b', 'q'],
        "default": "b",
        "description": "Exits the current menu or screen. This doesn't affect using Esc to exit menus.",
        "accepted": ['B', 'Q'],
    },
    {
        "name": "Confirm",
        "attr": "confirm",
        "type": "keybind",
        "conflict_group": "menu",
        "default": "y",
        "description": "Confirms any question which would be deemed too important to do by accident.",
        "accepted": "Any non-reserved key",
    },
    {
        "name": "Cancel",
        "attr": "deny",
        "type": "keybind",
        "conflict_group": "menu",
        "default": "n",
        "description": "Take a step back when what you're doing would not be worth it.",
        "accepted": "Any non-reserved key",
    },
    {
        "name": "Attack",
        "attr": "attack",
        "type": "keybind",
        "conflict_group": "battle",
        "default": "space",
        "description": "Primary attack in battles.",
        "accepted": "Any non-reserved key",
    },
    {
        "name": "Skill",
        "attr": "skill",
        "type": "keybind",
        "conflict_group": "battle",
        "default": "s",
        "description": "Uses the equipped skill.",
        "accepted": "Any non-reserved key",
    },
    {
        "name": "Ultimate",
        "attr": "ult",
        "type": "keybind",
        "conflict_group": "battle",
        "default": "w",
        "description": "Uses the equipped ultimate ability.",
        "accepted": "Any non-reserved key",
    },
    {
        "name": "Heal",
        "attr": "heal",
        "type": "keybind",
        "conflict_group": "battle",
        "default": "+",
        "description": "Uses the currently selected healing item.",
        "accepted": "Any non-reserved key",
    },
    {
        "name": "Forfeit",
        "attr": "forfeit",
        "default": "x",
        "type": "keybind",
        "conflict_group": "battle",
        "description": "Exits battle if fate willed your enemy to be too strong.",
        "accepted": "Any non-reserved key",
    },
]
