def volume_setting(name, attr, default, description):
    return {
        "name": name,
        "attr": attr,
        "type": "slider",
        "min": 0,
        "max": 10,
        "step": 1,
        "display": "volume",
        "default": default,
        "description": description,
        "accepted": "Off / 10%-100%",
    }


SETTINGS = [
    {
        "name": "Master volume",
        "attr": "master",
        "type": "slider",
        "min": 0,
        "max": 10,
        "step": 1,
        "display": "volume",
        "default": 10,
        "description": "The main dial. Controls how loud the entire game is.",
        "accepted": "Off / 10%-100%",
    },
    {
        "name": "Mute all audio",
        "attr": "disable_audio_completely",
        "type": "bool",
        "default": False,
        "description": "Silence all game audio temporarily. Turning this back off will revert your previous sound preferences!",
        "accepted": ['Off', 'On'],
    },
    {
        "name": "Music volume",
        "attr": "music",
        "type": "slider",
        "min": 0,
        "max": 10,
        "step": 1,
        "display": "volume",
        "default": 3,
        "description": "Adjust the soundtrack volume.",
        "accepted": "Off / 10%-100%",
    },
    {
        "name": "UI sound volume",
        "attr": "sound",
        "type": "slider",
        "min": 0,
        "max": 10,
        "step": 1,
        "display": "volume",
        "default": 10,
        "description": "Controls button clicks, selection chimes, and UI feedback.",
        "accepted": "Off / 10%-100%",
    },
    {
        "name": "Menu feedback sounds",
        "attr": "menu_feedback_sounds",
        "type": "bool",
        "default": True,
        "description": "Play navigation clicks and settings category sounds. Reward and equipment sounds stay enabled.",
        "accepted": ['Off', 'On'],
    },
    {
        "name": "Battle SFX volume",
        "attr": "sfx",
        "type": "slider",
        "min": 0,
        "max": 10,
        "step": 1,
        "display": "volume",
        "default": 10,
        "description": "How loud should combat hits and abilities pack a punch?",
        "accepted": "Off / 10%-100%",
    },
    {
        "name": "Ambient sound volume",
        "attr": "ambient",
        "type": "slider",
        "min": 0,
        "max": 10,
        "step": 1,
        "display": "volume",
        "default": 10,
        "description": "Background atmosphere - wind, rain, room tones and more!",
        "accepted": "Off / 10%-100%",
    },
    {
        "name": "Dialogue volume",
        "attr": "dialogue",
        "type": "slider",
        "min": 0,
        "max": 10,
        "step": 1,
        "display": "volume",
        "default": 10,
        "description": "Controls character voice lines and chatter.",
        "accepted": "Off / 10%-100%",
    },
    {
        "name": "Spatial audio",
        "attr": "spatial",
        "type": "bool",
        "default": False,
        "description": "Enables 3D directional sound cues. Hear where things are coming from!",
        "accepted": ['Off', 'On'],
    },
]
