SIMPLE_DESCRIPTIONS = {
    "battle_difficulty": "Easy: weaker. Normal: original. Hard: stronger. Extreme: better teamwork and new AI.",
    "battle_turn_delay": "How long to wait after you attack.",
    "battle_short_action_log": "Show only short action results, without turn messages.",
    "victory_celebration": "Choose how much animation plays after a win.",
    "animation_speed": "Choose animation speed from 0.5x to 2x. 1x is the usual speed.",
    "menu_transitions": "Play an animation when changing menus.",
    "flipboard_animations": "Animate letters when text changes.",
    "text_shine": "Play a moving shine across text.",
    "rainbow_text": "Show rainbow colors on decorated text.",
    "disable_startup_animation": "Go straight to the main menu when starting the game.",
    "battle_health_display": "Show enemy health as a number, a bar, or both.",
    "master": "Change the volume of all audio.",
    "sound": "Change the volume of menu and reward sounds.",
    "ambient": "Change background sound volume. Ambient sounds are not added yet.",
    "sfx": "Change the volume of battle hits.",
    "dialogue": "Change voice volume. Voice lines are not added yet.",
    "music": "Change music volume.",
    "disable_audio_completely": "Turn off all audio. Your volume settings are kept.",
    "spatial": "Play battle hits from the left or right speaker.",
    "attack": "Choose the key used to attack.",
    "heal": "Choose the heal key.",
    "skill": "Choose the skill key.",
    "ult": "Choose the ultimate key.",
    "back": "Choose the key used to go back.",
    "confirm": "Choose the key used to confirm an action.",
    "deny": "Choose the key used to cancel an action.",
    "forfeit": "Choose the key used to leave a battle.",
    "flash_effects": "Turn screen flashes on or off. This feature is not added yet.",
    "reduce_motion": "Turn off animations and moving text.",
    "auto_advance_dialogue": "Continue dialogue automatically. This feature is not added yet.",
    "double_tap_confirmation": "Press confirm twice instead of holding it for item actions.",
    "simplify_tutorials": "Use shorter instructions and simpler menu wording.",
    "sort_items_automatically": "Sort items whenever you open the inventory.",
    "remember_last_inventory_selection": "Remember your bag selection until you close the game.",
    "item_level_up_mode": "Upgrade one level at a time, or choose several levels.",
    "inventory_sorting": "Choose how to sort your items.",
    "inventory_sort_order": "Choose the direction used to sort your items.",
}
