SETTINGS = [
    {
        "name": "Flash Effects",
        "attr": "flash_effects",
        "type": "bool",
        "default": True,
        "description": "Enable visual flashes during certain game events.",
        "accepted": ["Off", "On"],
    },
    {
        "name": "Reduce Motion",
        "attr": "reduce_motion",
        "type": "bool",
        "default": False,
        "description": "Reduce or disable interface animations to minimize motion.",
        "accepted": ["Off", "On"],
    },
    {
        "name": "Auto-Advance Dialogue",
        "attr": "auto_advance_dialogue",
        "type": "bool",
        "default": False,
        "description": "Automatically continue dialogue after a short delay.",
        "accepted": ["Off", "On"],
    },
    {
        "name": "Double-Tap Confirmation",
        "attr": "double_tap_confirmation",
        "type": "bool",
        "default": False,
        "description": "Use a second key press instead of holding a key to confirm important actions.",
        "accepted": ["Off", "On"],
    },
    {
        "name": "Simplify Tutorials",
        "attr": "simplify_tutorials",
        "type": "bool",
        "default": False,
        "description": "Display shorter tutorials with only the essential information.",
        "accepted": ["Off", "On"],
    },
]
