SETTINGS = [
    {
        "name": "Flash effects",
        "attr": "flash_effects",
        "type": "bool",
        "default": True,
        "description": "Enable screen flashes during heavy attacks and events.",
        "accepted": ["Off", "On"],
    },
    {
        "name": "Disable ALL animations",
        "attr": "reduce_motion",
        "type": "bool",
        "default": False,
        "description": "Eviscerate every single animation - all of them at once.",
        "accepted": ["Off", "On"],
    },
    {
        "name": "Auto-advance dialogue",
        "attr": "auto_advance_dialogue",
        "type": "bool",
        "default": False,
        "description": "Continue dialogue without you having to mash Space.",
        "accepted": ["Off", "On"],
    },
    {
        "name": "Confirm with double-tapping",
        "attr": "double_tap_confirmation",
        "type": "bool",
        "default": False,
        "description": "Double-tap instead of holding to confirm important stuff.",
        "accepted": ["Off", "On"],
    },
    {
        "name": "Simplify tutorials",
        "attr": "simplify_tutorials",
        "type": "bool",
        "default": False,
        "description": "Display shorter tutorials with only the essential stuff.",
        "accepted": ["Off", "On"],
    },
]
