SETTINGS = [
    {
        "name": "Animation speed",
        "attr": "animation_speed",
        "type": "slider",
        "display": "animation_speed",
        "min": 0,
        "max": 10,
        "step": 1,
        "default": 0,
        "description": "Control how fast text animations play out!",
        "accepted": "Normal / 1.1×-1.9× / Instant",
    },
    {
        "name": "Menu transitions",
        "attr": "menu_transitions",
        "type": "bool",
        "default": True,
        "description": "Smooth transitions when moving between menus.",
        "accepted": ["Off", "On"],
    },
    {
        "name": "Skip startup animation",
        "attr": "disable_startup_animation",
        "type": "bool",
        "default": False,
        "description": "Bypass the startup animation and dive straight into the game.",
        "accepted": ["Off", "On"],
    },
    {
        "name": "Display enemy health as...",
        "attr": "battle_health_display",
        "type": "choice",
        "choices": ["Number", "Bar", "Both number and bar"],
        "default": "Both number and bar",
        "description": "Choose how enemy health is shown during battles.",
        "accepted": ["Number", "Bar", "Both number and bar"],
    },
]
