SETTINGS = [
    {
        "name": "Animation Speed",
        "attr": "animation_speed",
        "type": "choice",
        "choices": ["Instant", "Fast", "Normal"],
        "default": "Normal",
        "description": "Adjust the speed of tiny animations.",
        "accepted": ["Instant", "Fast", "Normal"],
    },
    {
        "name": "Menu Transitions",
        "attr": "menu_transitions",
        "type": "bool",
        "default": True,
        "description": "Enable transitions when opening and closing menus.",
        "accepted": ["Off", "On"],
    },
    {
        "name": "Item Level-Up Mode",
        "attr": "item_level_up_mode",
        "type": "choice",
        "choices": ["All", "One at a Time"],
        "default": "All",
        "description": "Choose how to level up your weapons & armor.",
        "accepted": ["All", "One at a Time"],
    },
    {
        "name": "Default Inventory Sorting",
        "attr": "inventory_sorting",
        "type": "choice",
        "choices": ["Name", "Level", "Rarity"],
        "default": "Name",
        "description": "Select how items are sorted when opening your inventory.",
        "accepted": ["Name", "Level", "Rarity"],
    },
    {
        "name": "Inventory Sort Order",
        "attr": "inventory_sort_order",
        "type": "choice",
        "choices": ["Ascending", "Descending"],
        "default": "Ascending",
        "description": "Choose whether inventory sorting is ascending or descending.",
        "accepted": ["Ascending", "Descending"],
    },
]
