SETTINGS = [
    {
        "name": "Enemy difficulty",
        "attr": "battle_difficulty",
        "type": "slider",
        "display": "difficulty",
        "min": 0,
        "max": 2,
        "step": 1,
        "default": 1,
        "description": "Set just how difficult you want your battles to be.",
        "accepted": ["Easy", "Normal", "Hard"],
    },
    {
        "name": "New turn starts after...",
        "attr": "battle_turn_delay",
        "type": "slider",
        "display": "duration",
        "min": 0.2,
        "max": 2.0,
        "step": 0.1,
        "default": 1.0,
        "suffix": "s",
        "description": "Set how much to wait after the last action in a turn.",
        "accepted": "0.2-2 sec.",
    },
    {
        "name": "Shorten action log",
        "attr": "battle_short_action_log",
        "type": "bool",
        "default": False,
        "description": "Display shorter battle messages to reduce read time.",
        "accepted": ["Off", "On"],
    },
    {
        "name": "Preview ability outcomes",
        "attr": "battle_preview_outcomes",
        "type": "bool",
        "default": True,
        "description": "Show the expected damage and effects before confirming an attack.",
        "accepted": ["Off", "On"],
    },
    {
        "name": "Victory celebration",
        "attr": "victory_celebration",
        "type": "slider",
        "display": "victory_celebration",
        "min": 0,
        "max": 3,
        "step": 1,
        "default": 2,
        "description": "How hard of a party do you wanna throw after a victory?",
        "accepted": ["Minimal", "Small", "Regular", "Extreme"],
    },
    {
        "name": "Show detailed action value",
        "attr": "show_detailed_action_value",
        "type": "bool",
        "default": False,
        "description": "Show exactly how much AV an attack consumes.",
        "accepted": ["Off", "On"],
    },
]
