SETTINGS = [
    {
        "name": "Default enemy difficulty",
        "attr": "battle_difficulty",
        "type": "choice",
        "choices": ["Very easy", "Easy", "Normal", "Hard", "Very hard"],
        "default": "Normal",
        "description": "Choose the default difficulty level for newly started battles.",
        "accepted": ["Very easy", "Easy", "Normal", "Hard", "Very hard"],
    },
    {
        "name": "New turn starts after...",
        "attr": "battle_turn_delay",
        "type": "slider",
        "min": 0.2,
        "max": 2.0,
        "step": 0.1,
        "default": 1.0,
        "description": "Adjust the delay between turns to speed up or slow down battles.",
        "accepted": "0.2 - 2 seconds",
    },
    {
        "name": "Shorten action log",
        "attr": "battle_short_action_log",
        "type": "bool",
        "default": False,
        "description": "Display shorter battle messages to reduce read time.",
        "accepted": ["Off", "On"],
    },
    {
        "name": "Enemy health display",
        "attr": "battle_health_display",
        "type": "choice",
        "choices": ["Bar", "HP", "Both"],
        "default": "Both",
        "description": "Choose how enemy health is shown during battles.",
        "accepted": ["Bar", "HP", "Both"],
    },
    {
        "name": "Preview ability outcomes",
        "attr": "battle_preview_outcomes",
        "type": "bool",
        "default": True,
        "description": "Show the expected damage and effects before confirming an attack.",
        "accepted": ["Off", "On"],
    },
]
