SETTINGS = [
    {
        "name": "Attack",
        "attr": "attack",
        "type": "keybind",
        "default": "space",
        "description": "Primary attack in battles.",
        "accepted": "Any non-reserved key",
    },
    {
        "name": "Heal",
        "attr": "heal",
        "type": "keybind",
        "default": "+",
        "description": "Uses the currently selected healing item.",
        "accepted": "Any non-reserved key",
    },
    {
        "name": "Skill",
        "attr": "skill",
        "type": "keybind",
        "default": "s",
        "description": "Uses the equipped skill.",
        "accepted": "Any non-reserved key",
    },
    {
        "name": "Ultimate",
        "attr": "ult",
        "type": "keybind",
        "default": "w",
        "description": "Uses the equipped ultimate ability.",
        "accepted": "Any non-reserved key",
    },
    {
        "name": "Back",
        "attr": "back",
        "type": "keybind",
        "allowed_keys": ["b", "q"],
        "default": "b",
        "description": "Returns to the previous menu.",
        "accepted": ["B", "Q"],
    },
    {
        "name": "Confirm",
        "attr": "confirm",
        "type": "keybind",
        "default": "y",
        "description": "Confirms the current selection.",
        "accepted": "Any non-reserved key",
    },
    {
        "name": "Cancel",
        "attr": "deny",
        "type": "keybind",
        "default": "n",
        "description": "Cancels the current action or closes a menu.",
        "accepted": "Any non-reserved key",
    },
    {
        "name": "Forfeit",
        "attr": "forfeit",
        "default": "x",
        "type": "keybind",
        "description": "Forfeits the current battle after confirmation.",
        "accepted": "Any non-reserved key",
    },
]
