SETTINGS = [
    {
        "name": "UI sound volume",
        "attr": "sound",
        "type": "slider",
        "min": 0,
        "max": 10,
        "step": 1,
        "display": "volume",
        "default": 10,
        "description": "Controls menu clicks, cursor movement and other interface sounds.",
        "accepted": "Off / 10%-100%",
    },
    {
        "name": "Battle SFX volume",
        "attr": "sfx",
        "type": "slider",
        "min": 0,
        "max": 10,
        "step": 1,
        "display": "volume",
        "default": 10,
        "description": "Controls attacks, abilities and other battle sound effects.",
        "accepted": "Off / 10%-100%",
    },
    {
        "name": "Music volume",
        "attr": "music",
        "type": "slider",
        "min": 0,
        "max": 10,
        "step": 1,
        "display": "volume",
        "default": 3,
        "description": "Controls the volume of background music.",
        "accepted": "Off / 10%-100%",
    },
    {
        "name": "Spatial audio",
        "attr": "spatial",
        "type": "bool",
        "default": False,
        "description": "Makes sounds appear to come from their in-game direction.",
        "accepted": ["Off", "On"],
    },
]
